### ISSUE TITLE
Scalability of methods pattern

### ISSUE THREAD

**Issue by ramijarrar** [meteor/todos#100]
The current pattern of exporting each individual method as a constant (i.e "insert", "remove", etc.) will lead to conflicts in apps that have multiple collections. 

Something like this:
```
import { insert } from 'foo/methods.js';
import { insert } from 'bar/methods.js';
```

Now obviously we could use names that are more specific (i.e "insertList", "removeList" etc.) but that reeks an awful lot of the "magic string names" which ValidatedMethod sought to rid us of.

Any suggestions here?

**Comment by stubailo** [comment]
You can change the name when you import:

```js
// Option 1
import { insert as insertFoo } from 'foo/methods.js';

insertFoo.call(...);

// Option 2
import * as fooMethods from 'foo/methods.js';

fooMethods.insert.call(...);
```

Does that look like a good option?
