### ISSUE TITLE
User Accounts configuration should not be loaded only on client 

### ISSUE THREAD

**Issue by mlecoq** [meteor/todos#113]
In todos example, the user accounts configuration is made at client side : 
https://github.com/meteor/todos/tree/master/imports/startup/client

Contrary to what is explained in user account core documentation : 
https://github.com/meteor-useraccounts/core/blob/master/Guide.md#configuration-api

Putting the configuration at client side leads to an issue if you want to verify emails : no email is sent at user creation.

**Comment by tmeasday** [comment]
Thanks @mlecoq, you are correct. We should update the guide also.

**Comment by hwillson** [comment]
This work was completed via PR #149 (and the relevant Guide sections look okay).
