### ISSUE TITLE
Todos not visible in lists on iOS

### ISSUE THREAD

**Issue by Jurredc** [meteor/todos#114]
Hello

I'm currently experimenting with the Todos example on iOS but the todos in the list do not become visible when I switch between the different lists.

To be sure I didn't make a mistake I just cloned the repository about 15 minutes ago and ran it on the iOS simulator.

When I tap on a list it is shown on the right side of the screen, only the todos do not become visible. The loading message also doesn't show up.

Once I add a new todo, the entire list becomes visible. Switching to another list and back will show the screen empty again.

Another thing I noticed is when I click on 'Join' the right side will be blank. By tapping on 'Sign in' and then again on 'Join' the page is shown correctly.

In the browser everything works fine as expected.

Feedback is much appreciated.

Thanks

**Comment by Herteby** [comment]
I'm getting the same thing too!

**Comment by jdonzet** [comment]
Me too

**Comment by gg2001** [comment]
Same for me

**Comment by Lenin7** [comment]
Any comments from MDG?

**Comment by johnsonchandra** [comment]
same for me.
It affects not just as ios-device(means cordova), but in mobile browser (safari) on iOS too.
I believe it must be something to do with the less/css.

**Comment by Lenin7** [comment]
Does anyone know any of the reasons why the todos example uses less over sass?

**Comment by Jurredc** [comment]
@johnsonchandra Were you able to solve this issue?

Can you share the steps you've taken to solve it?

Thanks

**Comment by tmeasday** [comment]
@dominicnguyen it seems the layout has broken on iOS. If you have a sec today can we look at this.

**Comment by tmeasday** [comment]
Fixed.
