### ISSUE TITLE
Optimistic UI & Method Locations

### ISSUE THREAD

**Issue by Incisive** [meteor/todos#115]
The general method of accomplishing this is to define the methods on both the client and the server, but I'm only seeing it imported on the server portion of the code in this example, including the react branch.

Is this no longer necessary for optimistic updates?

Thanks!

**Comment by tmeasday** [comment]
The methods are imported at the place they are used on the client. For example: https://github.com/meteor/todos/blob/master/imports/ui/components/lists-show.js#L13-L18

**Comment by Incisive** [comment]
Thanks Tom,  I wasn't aware that `mdg:validated-method` was a wrapper around `Meteor.methods` until looking up the package.

Thanks again!
