### ISSUE TITLE
Can't load npm module 'autoprefixer'

### ISSUE THREAD

**Issue by shirk3y** [meteor/todos#116]
Error occurs on branch 'react':

=> Errors prevented startup:

   While minifying app stylesheet:
   error: Can't load npm module 'autoprefixer' from
   packages/minifier-postcss_plugin.js. Check your Npm.depends().

**Comment by Emielangelaan** [comment]
How did you solve your issue?

**Comment by shirk3y** [comment]
I'm not sure, but `npm install autoprefixer` should do the job

**Comment by tmeasday** [comment]
Hey, you need to `meteor npm install` before running: https://github.com/meteor/todos#running-the-app

**Comment by fideo** [comment]
It´s true this solved the problem `meteor npm install` Thanks
