### ISSUE TITLE
No module 'faker'

### ISSUE THREAD

**Issue by shirk3y** [meteor/todos#117]
Error occurs on branch 'react':

Unable to resolve some modules:

  "faker" in /Users/shirkey/work/lolvoice/imports/api/todos/todos.js
(web.browser)

Consider running: meteor npm install --save faker

**Comment by tmeasday** [comment]
Sounds like you need to run `npm install`: https://github.com/meteor/todos/blob/master/README.md#running-the-app

**Comment by shirk3y** [comment]
Ok, it solved the issue, thanks!
