### ISSUE TITLE
Test helper packages

### ISSUE THREAD

**Issue by hwillson** [meteor/todos#119]
Hi guys! I find the test helper packages (publication-collector, the modified factory package, and stub-collections) to be quite helpful. Are there any plans to publish these, or would you be open to PR's to help get them ready? Thanks!

**Comment by hwillson** [comment]
Just to add (since I know you guys are busy) - if you prefer, I can volunteer to take ownership of them, clean them up a bit, publish, and support them. Unless of course you guys already have plans to do this. Let me know - thanks!

**Comment by msio777** [comment]
Hi @hwillson  do you make working publication-collector package because I got this error #120 
Thanks

**Comment by hwillson** [comment]
Hi @msio777 - commented in #120.

**Comment by tmeasday** [comment]
@hwillson I would totally love you to take over them and publish them yourself. Some notes:

1. `publication-collector`: This one works pretty well right now but I haven't tested it much outside of the todos app.

2. `factory`: I'm not sure what the best thing to do with this one is. @timbotnik and I basically rewrote `dburles:factory` to use different style of object creation in order to allow creation of "datasets" without having to write to Mongo. The best thing would be to merge it into `dburles:factory` I think, but it's pretty non-trivial to do. I don't think there's much long term benefit in maintaining two packages with basically the same API.

  PS I'd also love to see a non-globals based API for that too. Like:

```js
  import todosFactory from '/todos/factory.js';
  todosFactory.create();

  // rather than
  Factory.create('todos');
```


3. `stub-collections` - I think this one is pretty good as is, but definitely would love someone to maintain it!

**Comment by tmeasday** [comment]
cc @dburles

**Comment by dburles** [comment]
Hey @tmeasday I suppose we could release it as version 2.0 of the package (without backwards compatibility).

**Comment by hwillson** [comment]
Great, thanks guys! @tmeasday - I'll start by breaking out `publication-collector` and `stub-collections`, adding a bit more info to the docs, and getting them published. I'll then take a look at the factory approach; @dburles a 2.0 version sounds like a great idea. I could clean things up a bit first to get rid of the globals, and we can then re-visit. We'll be in touch!

**Comment by msio777** [comment]
@hwillson  great I'm looking forward to it

**Comment by hwillson** [comment]
Hi guys - sorry for the delayed follow up on this. I've broken a new version of the first package (`stub-collections`) out [here](https://atmospherejs.com/hwillson/stub-collections). More coming soon. Thanks!

**Comment by dburles** [comment]
Hey @hwillson @tmeasday I've gone ahead and setup a new branch for version 2 https://github.com/versolearning/meteor-factory/tree/two

**Comment by hwillson** [comment]
Awesome @dburles, thanks!

**Comment by hwillson** [comment]
Quick update based on #136 - @johanbrook is going to look into splitting out the PublicationCollector package (thanks @johanbrook!).

**Comment by johanbrook** [comment]
⚡

Thanks for referencing here as well, @hwillson !

**Comment by johanbrook** [comment]
Alright, extracted to GitHub repo and published to Atmosphere:

- https://github.com/johanbrook/meteor-publication-collector
- https://atmospherejs.com/johanbrook/publication-collector

Added some basic Mocha tests and fixed README a bit.

**Comment by tmeasday** [comment]
Looks great @johanbrook. 

If you get a sec, send us a PR to switch out the dependency here and at at the guide!

**Comment by johanbrook** [comment]
For sure :)

Question: did you guys have any plans on next steps with this package, feature wise? I read here and there that "it can be improved greatly". I'd be keen to listen.

**Comment by tmeasday** [comment]
I can't recall exactly -- I'd have to play with it in an app again, but I can think of two main thrusts:

1. I'm pretty sure I hacked it together (based on @stubailo's simple-rest code) in a short period of time, so I can't really vouch for the underlying code.

2. Does it support publications changing reactively as you call methods/write to Mongo? That'd be the obvious place to take it I think.

**Comment by johanbrook** [comment]
Gotcha, thanks! The code is very "clean and minimal", and it seems to do what it's supposed to do so far.

**Comment by dburles** [comment]
@johanbrook Could be updated to ES6 :)

**Comment by johanbrook** [comment]
@dburles You mean imports? The code pretty much uses ES2015 syntax already :)

**Comment by dburles** [comment]
@johanbrook you're right, at a glance what stood out was that it could probably be expressed in the new class syntax!

**Comment by johanbrook** [comment]
@dburles True true. If we'd like that, don't think it'll hurt in this case.

**Comment by hwillson** [comment]
Both the `publication-collector` and `stub-collections` packages have been moved into their own separate packages ([johanbrook:publication-collector](https://atmospherejs.com/johanbrook/publication-collector) and [hwillson:stub-collections](https://atmospherejs.com/hwillson/stub-collections) respectively). The custom `factory` package is going to stay as is (for now anyways - if anyone wants to revisit it, let me know). Closing!
