### ISSUE TITLE
Componentize Blaze Templates

### ISSUE THREAD

**Issue by tmeasday** [meteor/todos#12]
Follow all the patterns from the blaze article

**Comment by stubailo** [comment]
```
Error: Duplicate ReactiveDict name: list.XrcFWRsb2NX5ftt54
    at Function.ReactiveDict._registerDictForMigrate (migration.js:13)
    at new ReactiveDict (reactive-dict.js:25)
    at null.<anonymous> (lists-show.js:10)
    at template.js:116
    at Function.Template._withTemplateInstanceFunc (template.js:457)
    at fireCallbacks (template.js:112)
    at null.<anonymous> (template.js:192)
    at fireCallbacks (view.js:279)
    at Object.Tracker.nonreactive (tracker.js:589)
    at view.js:276
```

This happens if you open the app, click sign in, then click back on the first list in the sidebar.

**Comment by tmeasday** [comment]
Right. Maybe this reactive dict pattern doesn't work so well after all?

What I'd like that to do is reset the reactive dict named `list.XrcFWRsb2NX5ftt54` to the default state. But I guess it doesn't do that (if it doesn't reset it, the state of the list would remain, which I think might be quite weird).

Do you think we should make changes to reactive dict to allow this (somehow), or just not bother with the HCR stuff?

**Comment by tmeasday** [comment]
I think this ticket is resolved apart from the above

**Comment by stubailo** [comment]
My initial instinct was ditching the HCR migration, but different people have varying opinions about how useful that feature is. I feel like it's not worth jumping through hoops in your code just to get a small advantage when developing this stuff.

One way would be to make a simple function that checks if that reactive dict ID has been initialized before, and if it has just uses the existing one and clears it? Perhaps that's what we should do by default.. not sure.

**Comment by tmeasday** [comment]
Yeah I don't see a big downside in that being the default. The only problem would be if somehow you used the same reactive dict in two different files, we would no longer warn you. Still I think that'd be reasonably easy to work out?

**Comment by tmeasday** [comment]
Ok, going to stop doing this in the short term. https://github.com/meteor/meteor/issues/5647
