### ISSUE TITLE
faker/minifier errors

### ISSUE THREAD

**Issue by janat08** [meteor/todos#133]
"faker" in /C/Users/ALERATOR/todos-master/imports/api/todos/todos.js
(os.windows.x86_32)

Consider running: meteor npm install --save faker

=> Errors prevented startup:

   While minifying app stylesheet:
   error: Can't load npm module 'autoprefixer' from
   packages/minifier-postcss_plugin.js. Check your Npm.depends().

=> Your application has errors. Waiting for file change.

Running save faker doesn't help.

**Comment by tmeasday** [comment]
Sounds like you may need to run `meteor npm install`?

**Comment by janat08** [comment]
true that, sorry

**Comment by hwillson** [comment]
`meteor npm install` fixed the issue - closing.
