### ISSUE TITLE
React branch uses reactRouter not flowRouter

### ISSUE THREAD

**Issue by TimeBandit** [meteor/todos#134]
The meteor guide emphasises and explains flowRouter but then the react branch of the todos app uses reactRouter. I think it's a bit of a discrepancy making the guide out of synch with the app code.

**Comment by lorensr** [comment]
I think it's more that the Guide recommends FR for Meteor in general, and not necessarily for React, and just doesn't want to get into explaining multiple routers. React router is better for people coming from React, and perhaps is better (see eg Base switching to it). Let's see what Tom thinks

**Comment by TimeBandit** [comment]
Yes I see your point and it is a good point but if that were the case it could be argued that the todos-react example is servicing people coming from React into Meteor better than people coming from Meteor into React. 

- Having said that I guess I felt that MDG were endorsing FR by using it in the guide. 

- As far as the forums go they seem a bit neutral as far as which one people generally prefer. 

- As for consistency I think it's important at least for relatively new Meteor users such as myself to see the guide and the example app go hand in hand in order to read the theory and then see it in actions and understand the code with the minimum of fuss and extra learning.

**Comment by tmeasday** [comment]
In the React guide, we mention that both routers are commonly used with Meteor: http://guide.meteor.com/react.html#routing

We went with React Router for the React todos because it's more useful for people to see the contrast of how they are used. You can compare it to how Flow Router is used in the Blaze example in a pretty straightforward way.

**Comment by TimeBandit** [comment]
fair point thanks :)
