### ISSUE TITLE
lists.insert validator

### ISSUE THREAD

**Issue by antonioandrade** [meteor/todos#135]
Hey all. 

I'm wondering what the reasoning behind https://github.com/meteor/todos/blob/b2c540a191199736c36362342f027e2df99e2061/imports/api/lists/methods.js#L15 could be. Shouldn't it read something like `Lists.schema.validator()`?

For reference, this comes from https://github.com/siegesmund/SwiftDDP/issues/40#issuecomment-218628214

**Comment by tmeasday** [comment]
The idea is that there's one schema for the full collection and other for that specific API (ie. the method). You can't necessarily as a client decide all the fields that is put into the list. Actually in this case you can't decide any of them!

**Comment by hwillson** [comment]
Question answered - closing.
