### ISSUE TITLE
PublicationCollector isn't picking up documents from publication

### ISSUE THREAD

**Issue by johanbrook** [meteor/todos#136]
Hi!

I'm using PublicationCollector for some package tests. But I'm not getting anything passed to the callback to `.collect()`.

I traced it down, and it seems like the `added()` callback in `PublicationCollector` isn't called when returning a simple cursor from a publication, and thus documents aren't added to the collector. This is how it's done in this Todo example. It works when calling `this.added` manually in a publication.

Is Meteor really calling `added` under the hood when returning a `Cursor`?

**Comment by tmeasday** [comment]
> Is Meteor really calling `added` under the hood when returning a Cursor?

Yes!

I'm confused by what you are saying here: when you do the same thing as how it's done in Todos it doesn't work, even though it works in Todos?

Do you have a simple reproduction?

PS I'm looking for a maintainer of publication-collection if you are interested. I think @hwillson was interested but I guess he hasn't had time yet.

**Comment by johanbrook** [comment]
Never mind, it was me being in tired-end-of-day-mode-and-missed-out-on-a-simple-detail. All good and works 👌. Sorry about that.

P.S. I'd love to maintain this. I think testing publications is a vital thing (and also adding tests for this package ;)). I can extract this to a separate repo and package, like with the `meteor-stub-collections` package, if you give green light. Thanks!

**Comment by tmeasday** [comment]
Sure! Do it!! I guess we should double check if @hwillson has already done
it first I suppose :)

**Comment by johanbrook** [comment]
Righty, holding off until then. He hasn't got any public repo on this though.

**Comment by tmeasday** [comment]
I think it's probably reasonable to guess that he hasn't. I don't see much
on atmosphere (just one person who published it without a github repo)

**Comment by hwillson** [comment]
Yes please @johanbrook, by all means please go ahead! Sorry about the delay on this @tmeasday - I just added a new member to my family so my available free time has been drastically reduced (and my caffeine levels have been significantly increased). Looking forward to seeing this broken out - thanks guys!

**Comment by hwillson** [comment]
Just to add @johanbrook - my schedule should be back to normal in a week or so, so if it hasn't been split out by then, I can tackle it. Thanks again!

**Comment by johanbrook** [comment]
Thanks for informing, @hwillson, congratulations on new member! 🎉

**Comment by tmeasday** [comment]
Congrats @hwillson !
