### ISSUE TITLE
Factory package

### ISSUE THREAD

**Issue by dburles** [meteor/todos#138]
Some options:

A. Merge this into dburles:factory and release as 2.0 (not backwards compatible with 1.0) update on atmosphere.
B. Keep the atmosphere version at 1.0, update this package to use modules and publish on npm.
C. A and publish on npm in the future.

I think I'm leaning towards B now that the API will change due to module support.

**Comment by tmeasday** [comment]
Sure. I guess the one thing holding us back from publishing on npm would be the dependency on Meteor's `mongo` package.

Perhaps we could make a thin wrapper that takes the generic npm "obj" factory package and knows how to call into mongo?

**Comment by dburles** [comment]
That sounds interesting can you expand on that a little?

**Comment by kachkaev** [comment]
The `meteor/factory` packages seems to be gone now – I can't add it to a project using `meteor add factory`. What would you suggest to used instead, e.g. in 
https://github.com/meteor/todos/blob/master/imports/api/lists/lists.js#L3 ?

**Comment by detrohutt** [comment]
@tmeasday I'm working on a project based off of this repo and am now starting to write tests. At this point should I be using dburles:factory or the local implementation of factory in this repo?

**Comment by tmeasday** [comment]
Apologies for the slow responses:

> That sounds interesting can you expand on that a little?

I mean we write a npm factory package that just produces objects, probably in a "dataset" similar to the implementation in todos. Then a wrapper around that takes the dataset and inserts it into the relevant mongo tables, in Meteor.

> At this point should I be using dburles:factory or the local implementation of factory in this repo?

I guess `dburles:factory` is better supported at this point. The only reason to use the one in here is that it can generate a set of objects without doing inserts into the db. AFAIK (could be wrong), @dburles' factory doesn't yet allow you to do that (ie. `Factory.build` across multiple collections).

**Comment by dburles** [comment]
Closing as we're now using `dburles:factory`
