### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by tmeasday** [meteor/todos#14]
- [ ] Test methods on both sides
- [ ] Test publications on both sides

Look at using: https://github.com/anticoders/gagarin to build these.

**Comment by tmeasday** [comment]
Please add/comment about any tests which you think we should have @stubailo

**Comment by stubailo** [comment]
1. Adding new task
2. Deleting task
3. Editing task content
3. Making list private (mobile and desktop)
4. Deleting list (mobile and desktop)
5. Changing list title (mobile and desktop)
6. Registering
7. Logging in
8. Being redirected to a list when you go to the home page

**Comment by tmeasday** [comment]
I think these sound like acceptance tests actually, let's move this list here

**Comment by stubailo** [comment]
Oh, oops. I miscategorized.

**Comment by shilman** [comment]
@tmeasday not sure the right place to log this, but current status of running integration tests

> meteor test --full-app --driver-package practicalmeteor:mocha

1. Generates lots of warnings as described in https://github.com/practicalmeteor/meteor-mocha/issues/19
2. Does not generate any test output in browser, despite the presence of some `*.app_tests.js` files

![mocha](https://cloud.githubusercontent.com/assets/488689/14226626/d3dc7a6e-f921-11e5-888e-9e3b88197132.png)

There are also a number of integration tests defined in `package.json`, which is confusing without documentation. I understand that it's a work in progress. Happy to share error logs if it's useful or help debug with a little guidance.

Thanks!
