### ISSUE TITLE
app-prod-security package

### ISSUE THREAD

**Issue by peterpetre** [meteor/todos#145]
Hello, could you explain me how can i use it?

```
Package.describe({
  summary: 'Loads some useful packages for security, but only in production',
  prodOnly: true,
  documentation: null,
});

Package.onUse(function(api) {
  api.versionsFrom('1.2.1');

  api.use([
    'browser-policy',
    'force-ssl',
  ]);
});
```

**Comment by hwillson** [comment]
Sure - the local `app-prod-security` package is really just an umbrella package, that when included will include the other packages listed as dependencies (in this case [browser-policy](https://atmospherejs.com/meteor/browser-policy) and [force-ssl](https://atmospherejs.com/meteor/force-ssl)). It was created this way to leverage the [`prodOnly`](http://docs.meteor.com/api/packagejs.html#Package-describe) option that packages support, that when set will make sure this package (and its dependencies) are only bundled into production builds. This keeps them disabled (and absent) when running the todos app locally for example.
