### ISSUE TITLE
Reset password workflow will not work

### ISSUE THREAD

**Issue by jdivy** [meteor/todos#148]
I was just testing the password reset functionality in an app I'm building based loosely on this one.  Long story short, according to the documentation of the useraccounts package (https://github.com/meteor-useraccounts/core/blob/master/Guide.md#configuration-api), configuration should be done on both the client and server.

Specifically, I was seeing this issue (https://github.com/meteor-useraccounts/core/issues/277#issuecomment-73570792), and a comment at the end of the thread pointed me in the right direction.

I'll create a pull request with my particular solution shortly.

Note: I'm not sure how many people this would affect anyway, but it was a little frustrating when I expected the demo app to have all the basics working.

**Comment by LiamBigelow** [comment]
Would also be wise to include the verifyEmail route
```
AccountsTemplates.configureRoute('verifyEmail', {
  name: 'verify-email',
  path: '/verify-email',
});
```
Otherwise the email verification options hit a page not found.

**Comment by jdivy** [comment]
Looks like I missed a duplicate issue #113 which I think is also fixed by my pull request.

**Comment by LiamBigelow** [comment]
Correct. Email verification is fixed by this pull request, provided the route is configured.
