### ISSUE TITLE
React branch > i18n/en.json usage

### ISSUE THREAD

**Issue by sahanDissanayake** [meteor/todos#150]
Hi, I dont see where you are making use of this file ? 
Have I missed something ?

Where does the translation for this line comes from please ? very confused
https://github.com/meteor/todos/blob/01e0d749e1d4544a080e8dffaf9c0e8ff803e2f6/imports/ui/components/lists-show.js#L70

**Comment by Nolapete** [comment]
The tap:i18n package uses the en.i18n.json found in the i18n folder for English.  From what I see you need to create the translation files in that folder.  An excerpt from https://atmospherejs.com/tap/i18n

> Step 3: Define translations in JSON or YAML format:
> 
> i18n/en.i18n.json
> 
> { "hello": "Hey there" }
> i18n/fr.i18n.json
> 
> { "hello": "Bonjour" }
> i18n/es.i18n.yml
> 
> hello: Hola

**Comment by sahanDissanayake** [comment]
yeah all good.. Thanks
