### ISSUE TITLE
Installation of devDependencies in todos-react not skipped when installing node modules

### ISSUE THREAD

**Issue by tab00** [meteor/todos#151]
In the react branch, installation of devDependencies are not skipped when using
`npm install --production`
or
```
npm set config production
npm install
```

The resulting app in production has around 17,000 unnecessary files.

The problem does not appear in the Blaze version (installation of devDependencies are skipped as expected).

**Comment by tab00** [comment]
I have found that removing the following from npm-shrinkwrap.json fixes the problem:
```
enzyme
eslint
eslint-config-airbnb
eslint-plugin-meteor
eslint-plugin-react
meteor-node-stubs
```

**Comment by hwillson** [comment]
The shrinkwrap files have been removed from both the `master` (Blaze) and `react` branches, so this is no longer an issue. Closing.
