### ISSUE TITLE
Make sure email login is enforced at DDP level + tests

### ISSUE THREAD

**Issue by stubailo** [meteor/todos#16]
~~Right now, you could use Meteor.loginWithPassword to log in with a username from the console. We should prevent that, and test that you can't log in with invalid stuff.~~

That's not correct - apparently useraccounts enforces it for you! Wow.

https://github.com/meteor-useraccounts/core/blob/master/Guide.md#disabling-client-side-accounts-creation

@splendido, can you help me understand more about exactly what useraccounts is guaranteed to enforce?

**Comment by splendido** [comment]
useraccounts uses a server-side method to register new users both to enforce additional fields validation (which could be easily avoided on the client-side...), add some additional hook and provide support for ReCaptcha (still not fully tested). To do so, use of `Accounts.createUser` from the client side id prohibited by setting `forbidClientAccountCreation` to true: see [here](https://github.com/meteor-useraccounts/core/blob/4f2d4067e7e4ee6146de9692ec4699c9580068e7/lib/server.js#L177-L179)
[Here](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L201) is where the call to `ATCreateUserServer` is triggered.


As for password login operations, regular `Meteor.loginWithPassword` is used [here](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L173).
Also for OAuth logins there's nothing special. See [here](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_social.js#L74-L91) the selection of the method to call based on the name of the selected service.


The only other thing enforced on the server-side is the email verification which takes place thanks to this [validateLoginAttempt callback](https://github.com/meteor-useraccounts/core/blob/4f2d4067e7e4ee6146de9692ec4699c9580068e7/lib/server.js#L110-L151) in case configuration options where set appropriately.

**Comment by stubailo** [comment]
Seems like it already does everything by default, then!

Awesome.
