### ISSUE TITLE
Is code in `imports/ui` really considered browser code by meteor?

### ISSUE THREAD

**Issue by scharf** [meteor/todos#165]
I followed the structure in this example with my typescript code. It turns out, that typescript complains about the usage of `window` and `document` in code that is in the `imports/ui` directory (see [issue 54](https://github.com/meteor-typescript/meteor-typescript-compiler/issues/54#issuecomment-232715623) on `meteor-typescript/meteor-typescript-compiler`).

I think the structure should suggest to put all UI related code into `imports/client`, or am I missing something here?

**Comment by hexsprite** [comment]
If you're using server side rendering you may wish to have UI code on both server and client.

**Comment by hwillson** [comment]
@hexsprite nailed it - if you know your UI related code will be client only though, you can definitely put it in `imports/client` if you prefer. Thanks!
