### ISSUE TITLE
Why does circleci.yml use node 5.2.0?

### ISSUE THREAD

**Issue by noahsw** [meteor/todos#168]
When running `meteor node -v`, I get `v0.10.46`. So why should circleci use a different version?

Thx!

**Comment by tmeasday** [comment]
Hey @noahsw -- The script installs Meteor also (which comes with a bundled version of node). All meteor-related things are run with `meteor node` or `meteor npm`, which ends up using the bundled version.

The circle version of node is used for chimp, which needs node 4+. With Meteor 1.4, we should be able to remove this.
