### ISSUE TITLE
where does _helpers come from?

### ISSUE THREAD

**Issue by veyronfei** [meteor/todos#179]
It's not a bug in the code. But maybe because I am quite new to javascript, so I don't quite understand the syntax. there is one line in todos-items.js line:20. todo: { type: Todos._helpers }. May I ask where is this property _helpers come from? I would like to use this reusable component pattern, but it doesn't work in my probject. Thanks in advance.

**Comment by hwillson** [comment]
Hi @veyronfei - it's coming from the [dburles:collection-helpers](https://atmospherejs.com/dburles/collection-helpers) package. See:

https://github.com/dburles/meteor-collection-helpers/blob/efd75bb8ada7b8a32295707ac924abc379bd6b5f/collection-helpers.js
