### ISSUE TITLE
Error: EMFILE: too many open files, scandir

### ISSUE THREAD

**Issue by dandoyon** [meteor/todos#183]
=> App running at: http://localhost:3000/
/Users/tet/.meteor/packages/coffeescript/.1.1.4.1ipkcop++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: EMFILE: too many open files, scandir '/Users/test/Projects/todos/node_modules/es5-ext/test/reg-exp/#/replace'
    at Error (native)

**Comment by hwillson** [comment]
The todos app has been updated to use a more recent version of Meteor (currently 1.4.1.1). Recent versions of Meteor do a better job of pruning the `node_modules` directory, so this should no longer be an issue. Closing for now - let me know if you encounter this issue again.

**Comment by rahul606** [comment]
I am still having the same problem with latest version of Meteor 1.4.1.1

**Comment by rahul606** [comment]
Found the solution: 

♆ > cat /etc/profile
# System-wide .profile for sh(1)

if [ -x /usr/libexec/path_helper ]; then
    eval `/usr/libexec/path_helper -s`
fi

if [ "${BASH-no}" != "no" ]; then
    [ -r /etc/bashrc ] && . /etc/bashrc
fi
ulimit -n 4096

**Comment by hwillson** [comment]
@rahul606 Glad to hear you found a solution. For others landing on this issue, this was discussed in quite a bit of detail in meteor/meteor#6952. For a great solution to this problem check out @abernix's gist: https://gist.github.com/abernix/a7619b07b687bb97ab573b0dc30928a0
