### ISSUE TITLE
Understanding {{_ 'layouts.appBody.login'}} 

### ISSUE THREAD

**Issue by mitchswaldman** [meteor/todos#186]
Hello,

In the app body html file, you use this template helper: 
```
<div class="btns-group">
     <a href="{{pathFor 'signin'}}" class="btn-secondary">
              {{_ 'layouts.appBody.login'}} 
      </a>
      <a href="{{pathFor 'join'}}" class="btn-secondary">
              {{_ 'layouts.appBody.join'}}
      </a>
</div> 
```

I have two questions.

1) Where does the _ helper function come from? I don't see it defined in the App_body.helpers.

2) This may be answered by the first question, but how is the string 'layouts.appBody.login` able to be resolved to a template? I don't see it declared anywhere in the code. 

Thanks!

**Comment by tmeasday** [comment]
Hi @mitchswaldman - it's i18n via the `tap:i18n` package: https://guide.meteor.com/ui-ux.html#i18n

**Comment by mitchswaldman** [comment]
Oh okay cool, so it's just converting a string. Gotcha. Thanks!
