### ISSUE TITLE
Error while running react branch

### ISSUE THREAD

**Issue by vicesalles** [meteor/todos#192]
runned meteor command and it's throwing this error:
TypeError: Package.describe is not a function
W20161006-15:33:56.397(2)? (STDERR)     at meteorInstall.todos-react.packages.app-prod-security.package.js (meteor://�app/todos-react/packages/app-prod-security/package.js:1:9)

**Comment by hwillson** [comment]
In your todos checkout, try running a `meteor reset`, followed by running the app again.
