### ISSUE TITLE
Error: Cannot find module '../core-js/object/assign'

### ISSUE THREAD

**Issue by tafelito** [meteor/todos#195]
Hi, is anyone having this issue in the react version with latest Meteor 1.4.2.1? I wonder if the repo is failing for the same reason

Thanks

**Comment by benjamn** [comment]
Ah, `babel-runtime` needs to be in the "dependencies" section of `package.json`. I'll make that change when I get back to a computer if no one beats me to it. @hwillison?

**Comment by tafelito** [comment]
Thanks @benjamn, that did the trick. I can close the issue

**Comment by hwillson** [comment]
Sure thing, I'll take care of it  - @tafelito, I'll re-open this until the update is done. Thanks!

**Comment by hwillson** [comment]
Done - thanks!
