### ISSUE TITLE
Add OAuth login with Google

### ISSUE THREAD

**Issue by stubailo** [meteor/todos#20]
It's a shame not to demo this, and perhaps this means we should build out account merging?

There's a decision to be made on how deep we want to go into the accounts rabbit hole - perhaps we could leave this for later.

**Comment by stubailo** [comment]
Going to leave for later. No time to get into accounts merging now. Perhaps we could ask for PRs for these.

**Comment by NickBusey** [comment]
I am currently building out an app based on the todos framework. Having Google oAuth already working would have saved me a bunch of time.

**Comment by abernix** [comment]
@NickBusey If you've already figured out which changes are necessary, do you mind making a contribution to the project and submitting a pull-request for what it took?  Others will appreciate the time you've saved them just in the way you would have appreciated not having done it! :wink:

**Comment by NickBusey** [comment]
I have not figured out the changes necessary.

**Comment by NickBusey** [comment]
Done https://github.com/meteor/todos/pull/217
