### ISSUE TITLE
Sass instead of Less

### ISSUE THREAD

**Issue by jdnichollsc** [meteor/todos#200]
Hi guys,

What do you think about to use **Sass** (scss) instead of **Less**?

Thanks in advance, Nicholls

**Comment by hwillson** [comment]
Hi @jdnichollsc - less is used internally by MDG, so they picked it when creating this reference application. A version of todos could just as easily be created/maintained using sass, stylus or any other css preprocessor for that matter. Sass has been used successfully with many Meteor projects, and is referenced in the [Meteor Guide](https://guide.meteor.com/build-tool.html#sass). Thanks!
