### ISSUE TITLE
Page not found "flickering" in React branch

### ISSUE THREAD

**Issue by germanliu** [meteor/todos#201]
Hi, I've installed the project and launched it using the React branch. 

I removed all the .less files to have the project without any css applied to it.

When you navigate through the lists, before you actually get to see the todos inside that list, you see a "Page not found" on the screen that disappears quickly.

I'm not exactly sure what is wrong here, but somewhere in the middle of the page transitions a page not found is shown. When you have all the css applied you are not able to see this.

Any idea what could be wrong?

Thanks in advance.

**Comment by hwillson** [comment]
We've made recent routing changes to the app, so this should no longer be an issue. See the latest `react` version. Thanks for reporting this!
