### ISSUE TITLE
[coffeescript] Tests running against JavaScript code

### ISSUE THREAD

**Issue by abernix** [meteor/todos#209]
Currently in the CoffeeScript version of this application (on the `coffeescript` branch) the unit tests are not really running the CoffeeScript code but rather the JavaScript code.

This came about in #206, but I'm opening this so it's not forgotten – even if it's on our minds. :wink:

**Comment by GeoffreyBooth** [comment]
Fixed via 78b5f79c749526bbcfe1157242e66fc49f2340b7 and 27dc58529f73635d3d2d28276fb04d540c733afb. The tests pass on the `coffeescript` branch. See also #210.
