### ISSUE TITLE
Failed deploying the todos app with Meteor Up

### ISSUE THREAD

**Issue by robort** [meteor/todos#220]
Hi guys,

I was trying to deploy the **react** branch in this todos app with [Meteor Up ](https://github.com/zodern/meteor-up), but the app failed to be accessible after deployment. 

I log this issue to this [todos](https://github.com/meteor/todos) repository because it doesn't happen when I was trying with [localmarket](https://github.com/meteor/localmarket)

Does anyone have ideas why this would happen and how to fix?

The failure phenomenon: 
- The app actually succeeds to be deployed to a local Vagrant VM (OS: Ubuntu 14.04 LTS) (e.g. named **abc**) with ROOT_URL [http://abc:3000](http://abc:3000), but if you open the link [http://abc:3000](http://abc:3000) in browser, it will be redirected automatically to [https://abc](https://abc), and you cannot access.

The mup.js configuration is as below:

```js
module.exports = {
  servers: {
    one: {
      host: 'abc',
      username: 'vagrant',
      // pem:
      password: 'vagrant'
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'todos',
    path: '../..',
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      PORT: 3000,
      ROOT_URL: 'http://abc',
      MONGO_URL: '', //Your MONGO URL,
    },

    // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
    dockerImage: 'abernix/meteord:base',
    deployCheckWaitTime: 300,

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },
};

```

Please kindly let me know if any more information is needed.

**Comment by zodern** [comment]
You will need to remove the [force-ssl](https://github.com/meteor/todos/blob/master/packages/app-prod-security/package.js#L12) package.

**Comment by robort** [comment]
@zodern thanks for reply.

However, it seems the force-ssl package is not explicitly included in the meteor packages of this project as I tried. 

```bash
> meteor remove force-ssl
force-ssl is not a direct dependency in this project.
```

Is it possibly enabled implicitly in the bundle after ```meteor build```?

**Comment by robort** [comment]
@zodern 

I tried setting ```meteor.buildOptions.debug``` to ```true```, and then the todos app can be deployed to [http://abc:3000](http://abc:3000), and is accessible from browser.  😈 

Any ideas how to make it still work when the debug setting is false?

The updated mup.js by setting debug to true.

```js
module.exports = {
  servers: {
    one: {
      host: 'abc',
      username: 'vagrant',
      // pem:
      password: 'vagrant'
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'todos',
    path: '../..',
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true,
      debug: true
    },
    env: {
      PORT: 3000,
      ROOT_URL: 'http://abc',
      MONGO_URL: '', //Your MONGO URL,
    },

    // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
    dockerImage: 'abernix/meteord:base',
    deployCheckWaitTime: 300,

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },
};

```

**Comment by zodern** [comment]
It is added by the `app-prod-security` package [here](https://github.com/meteor/todos/blob/master/packages/app-prod-security/package.js#L12). Since it is a production only package, it is not added in debug mode. It took me a while to solve this last month.

**Comment by robort** [comment]
@zodern thanks. It works after removing `force-ssl` from `app-prod-security`
