### ISSUE TITLE
Code Coverage? (React)

### ISSUE THREAD

**Issue by mackbrowne** [meteor/todos#229]
Im trying to use https://github.com/serut/meteor-coverage to track code coverage for my app.  

It doesn't seem that the plugin above works for this case, is up to date or I can't figure out how to properly configure it.  

Has anyone had success with this or a similar tool?

**Comment by hwillson** [comment]
Hi @mackbrowne - I'd suggest reaching out on the [Meteor forums](https://forums.meteor.com) or [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor). GH issues here are reserved for issues/feature requests with the `todos` app itself, which doesn't currently use `meteor-coverage`. Thanks!
