### ISSUE TITLE
Explain Factory.build() Method

### ISSUE THREAD

**Issue by salimakhtar786** [meteor/todos#234]
**I could not understand Factory.build() method** 

```
const todo = Factory.build('todo', { checked: false });

```
In this code what is `todo` inside `Factory.build('todo', { checked: false })`

Is it userdefine or predefine?
Please explain

**Comment by hwillson** [comment]
Hi @salimakhtar786 - issues here are reserved for `todos` bugs / feature requests. For help with understanding how `todos` works, your questions are better asked on the [Meteor forum](https://forums.meteor.com).

In this case, `Factory.build` is an API call from the [`dburles:factory`](https://atmospherejs.com/dburles/factory) package. You can find out more in that packages [API docs](https://github.com/versolearning/meteor-factory#build), but in a nutshell it's building a fake `todo` object that can be used within the test.
