### ISSUE TITLE
When we are using assert and when we are using chai in Testing

### ISSUE THREAD

**Issue by salimakhtar786** [meteor/todos#235]
Please explain when we are using assert and when we are using chai

`import { chai } from 'meteor/practicalmeteor:chai';`

**Comment by hwillson** [comment]
[`assert`](http://chaijs.com/guide/styles/#assert) is part of the `chai` library. Based on how the `chai` devs have set their package up, you can either import `assert` directly like this:

```js
import { assert } from 'meteor/practicalmeteor:chai';
assert.equal(...);
```

or just import `chai` and reference `assert` from it, like:

```js
import { chai } from 'meteor/practicalmeteor:chai';
chai.assert.equal(...);
```

`todos` uses both styles. 

Again though, usability questions like this are much better suited for the [Meteor forums](https://forums.meteor.com) (issues here are reserved for bugs / feature requests).
