### ISSUE TITLE
In my localhost I get "It looks like you are trying to access MongoDB over HTTP on the native driver port."

### ISSUE THREAD

**Issue by lexblagus** [meteor/todos#237]
Can I run without https on my **localhost**, just old plain regular **http**?

**Comment by hwillson** [comment]
Everything should run on http - where are you seeing this error message? Can you post a screenshot?

**Comment by lexblagus** [comment]
I was going to run all the comands again to provide a deeper info for you, and it have *just worked*.
Thanks!!!
