### ISSUE TITLE
Simplify a lists url to be '/:_id' instead of '/lists/:_id'

### ISSUE THREAD

**Issue by holgate** [meteor/todos#241]
I'm trying to learn Meteor using Todos as an example.

I want to simplify a list's url by removing the "/lists" part: i.e. rather than
`http://localhost:3000/lists/QeHMZa2z6EttCbnfH` I'd like the url to my list to be:
`http://localhost:3000/QeHMZa2z6EttCbnfH`

I originally thought this was easy: I'd simply
`FlowRouter.route('/lists/:_id', {`
to
`FlowRouter.route('/:_id', {`
in routes.js and it all seemed to work fine at first... until I tried navigating to /signin or /join.

It appears that FlowRouter is clashing with AccountsTemplates in useraccounts-configuration.js - in this configuration the system doesn't know that /signin isn't just another list.

Any idea how to resolve? I already tried moving the AccountsTemplates logic into FlowRouter unsuccessfully.

**Comment by abernix** [comment]
Hello,

These issues are reserved for reporting bugs or submitting PRs for the `todos` app.  The issue you have reported is not an actual bug with Meteor, but instead a question about how to use it.

There are many helpful resources available to help you with your problem, however, general questions are not accepted here.  Be sure to check out the [Meteor Guide](https://guide.meteor.com) and the [Documentation](https://docs.meteor.com) along with the ["Todos" example application](https://github.com/meteor/todos), and the [other tutorials](https://www.meteor.com/tutorials).

If you still need help, it's recommended you post your question to [StackOverflow using the `meteor` tag](https://stackoverflow.com/questions/tagged/meteor) or visit the [Meteor forums](http://forums.meteor.com) to discuss your problem with the Meteor community.

Thank you for your understanding!
