### ISSUE TITLE
Update React Todo to use TypeScript since PropTypes deprecation

### ISSUE THREAD

**Issue by dcantatore** [meteor/todos#245]
https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactproptypes

They suggest using the prop-types package but I think using TypeScript would be a better option since it is can be used with all javascript and not intended just for react. There are more pros and cons if searched, open to hear all thoughts.

**Comment by hwillson** [comment]
Thanks for the suggestion @dcantatore - we're going to stick with `PropTypes` for now. The latest version of `todos` in the `react` branch is now using the `PropTypes` package.
