### ISSUE TITLE
Improve pattern for list ownership to make it more explicit

### ISSUE THREAD

**Issue by stubailo** [meteor/todos#25]
Probably using a collection helper

**Comment by stubailo** [comment]
@tmeasday is the userId denormalization from Lists to Todos working? I looked at the Todos code and I can't understand what it's doing.

**Comment by tmeasday** [comment]
Is this done now?

**Comment by stubailo** [comment]
No, it involves changing this code to no longer retrieve the list: https://github.com/meteor/todos/blob/c5f66764155f68aaf664df06b50dde15be27b98b/packages/todos/methods.js#L79-L84

**Comment by tmeasday** [comment]
Gotcha

**Comment by stubailo** [comment]
38d3d4efe25d2cbd3ab56820f9181dffe98c4ef3
