### ISSUE TITLE
Figure out how to disable allow/deny

### ISSUE THREAD

**Issue by stubailo** [meteor/todos#29]
This can be as simple as adding deny rules for every collection

**Comment by stubailo** [comment]
@tmeasday is this somehow solved by collection 2? Back when we were going to make a new ValidatedCollection class or something, this could have been part of that, but it looks like we're not doing that anymore.

**Comment by tmeasday** [comment]
I think collection2 is designed to work *with* allow and deny if you want it to. But perhaps it could have an option to deny all?

**Comment by stubailo** [comment]
Yeah that's what I'm looking for.

**Comment by stubailo** [comment]
fc1ac605e529684242338bdaa5898d2172a55924
