### ISSUE TITLE
Make proper use of Less / CSS / PostCSS

### ISSUE THREAD

**Issue by tmeasday** [meteor/todos#4]

**Comment by stubailo** [comment]
Seems like lesshat is dead: https://github.com/madebysource/lesshat/issues/162

**Comment by stubailo** [comment]
Moved to autoprefixer thanks to @juliancwirko

https://github.com/meteor/todos/commit/a3254527b5638a18a1497c923c9365dca748b745

**Comment by stubailo** [comment]
Todos:

- [ ] Make sure we are actually using some reasonable portion of the LESS code
- [ ] Make sure the import structure is sane

**Comment by stubailo** [comment]
Should be good - we might want to revisit the package names at some point but that can be another time.
