### ISSUE TITLE
Should we use `throwStubExceptions` in methods so that we don't unnecessarily do optimistic stuff?

### ISSUE THREAD

**Issue by tmeasday** [meteor/todos#40]
For instance, when trying to remove the last public list. I think yes.

**Comment by stubailo** [comment]
Oh, yes - good idea. Although, are there situations where you wouldn't want that? I guess we can have an option to turn it off.

**Comment by tmeasday** [comment]
Yeah but I think it should probably be the default.

**Comment by stubailo** [comment]
d07f68bc1503a215d8efa13355783c5172f2534e
