### ISSUE TITLE
Use Methods package / remove allow deny code

### ISSUE THREAD

**Issue by tmeasday** [meteor/todos#5]

**Comment by stubailo** [comment]
Todos:

- [ ] Figure out how to simplify authorization code, especially in the case where a user owns a list, and we don't want them to be able to edit the todo items therein
- [ ] Figure out what to do about errors - right now we basically always assume that the operation will succeed; perhaps the failure is super unlikely if we do the UI right?

**Comment by tmeasday** [comment]
The UI/UX article talks about the pattern of optimistically assuming stuff will work and then doing something drastic if it fails (which is totally reasonable in the case where it will "definitely" work).

What I'd do normally is pop a flash notification, log something to the console, and then re-route somewhere that makes sense (if needed). We don't have flash notifications in todos, perhaps we just throw up an alert?

**Comment by stubailo** [comment]
Yeah I think we use alerts for this stuff in todos.

**Comment by stubailo** [comment]
OK I think we good
