### ISSUE TITLE
Fresh install gives ReferenceError: chai is not defined

### ISSUE THREAD

**Issue by Maxximus007** [meteor/todos#66]
Trying to install, but starting Meteor gives the following error:

W20160105-12:59:47.479(1)? (STDERR) ReferenceError: chai is not defined
W20160105-12:59:47.479(1)? (STDERR)     at meteorInstall.app.imports.api.lists.lists-tests.js (imports/api/lists/lists-tests.js:4:16)....

**Comment by ThisSentenceIsFalse** [comment]
'chai' seems to be the name of an Atmosphere package that, for some reason, had not been already added when you ran it. I installed it along with a few other packages (describe, before etc.) before attempting practicalmeteor:mocha on inspiration. Then ran into problems with imports referring folders incorrectly (server/fixtures.js). 
I managed to start it in the end, but it doesn't really seem to work correctly in the browser (?) It's probably a temporary package management + reorganizing issue (unless I've been missing something in the usage documentation, haven't been very thorough); judging by the evolution of the repository, it shouldn't be too long before the people at Meteor solve it.

**Comment by stubailo** [comment]
Ah my bad, didn't document this - there is a bug in the current 1.3 beta release, so I'm running from a branch of meteor. It should be fine when the next beta comes out, for now just remove the testing files since they don't do anything right now.

**Comment by stubailo** [comment]
19f5196b52e2c2894907d5376b1e7b83921ab64b

Ignored those files for now, will revert this commit when next 1.3 beta ships.
