### ISSUE TITLE
how do I run this?

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [meteor/todos#67]
Jesus ******* Christ, how do I run this? Why does it have to be so complicated? Why can't I just git clone it and run meteor from the main directory?

**Comment by stubailo** [comment]
You should be able to - does that not work for some reason?

**Comment by Laurentiu-Andronache** [comment]
Can you please do it in a console and print the log?

From what I guess, certain files and folders have to be moved into main/ before starting meteor for the first time. I just moved them all for good measure and it still doesn't work. Shouldn't the whole application be into a single directory though, and just run meteor into that directory? 

=> Started proxy.
=> Started MongoDB.
npm-container: updating npm dependencies -- autoprefixer...
=> Errors prevented startup:

   While processing files with less (for target web.browser):
   imports/client/components/lists-show.less:1: Unknown import: {}/main/client/less/imports.import.less

   While processing files with less (for target web.cordova):
   imports/client/components/lists-show.less:1: Unknown import: {}/main/client/less/imports.import.less

=> Your application has errors. Waiting for file change.

**Comment by stubailo** [comment]
It's possible that the application is currently broken, I'll take a look when I get home. But no you shouldn't have to move anything before running it.

**Comment by GregS2** [comment]
FWIW, I experienced problems after upgrading from Meteor 1.2 to 1.3 (beta). I wiped the app completely and re-cloned it, and that fixed the problem - the app now runs again, albeit with the same [missing functionality](https://github.com/meteor/todos/issues/68) I had on 1.2.
