### ISSUE TITLE
Error: Can't find npm module 'meteor/aldeed:simple-schema'.

### ISSUE THREAD

**Issue by Rongky** [meteor/todos#69]
When running todos in Ubuntu 14.04:

Error: Can't find npm module 'meteor/aldeed:simple-schema'. Did you forget to call 'Npm.depends' in package.js within the 'modules' package?

**Comment by arlinon** [comment]
Having same error on windows 10

**Comment by Chase-C** [comment]
I'm getting the same error on Arch

**Comment by thomasmery** [comment]
updating to latest beta fixed it for me
`meteor update --release 1.3-modules-beta.4`

**Comment by cheapRoc** [comment]
I just confirmed what @thomasmery said. 

This issue can be closed.

**Comment by stubailo** [comment]
Are you all running from a git checkout of meteor or something?

This file: https://github.com/meteor/todos/blob/master/.meteor/release

Is supposed to tell Meteor to run the right version of the tool. Is this feature not working for you all?
