### ISSUE TITLE
Get rid of packages.json

### ISSUE THREAD

**Issue by tmeasday** [meteor/todos#70]
We are installing autoprefixer via npm but not in the 1.3 way. I assume we can change this @stubailo?

**Comment by stubailo** [comment]
We should try the beta of this package: https://github.com/juliancwirko/meteor-postcss

Looks like it's supposed to work with 1.3, which I assume means we no longer need meteorhacks:npm.

**Comment by stubailo** [comment]
This has directions, we should try it out: https://github.com/juliancwirko/meteor-postcss/tree/meteor-1.3-in-progress

**Comment by tmeasday** [comment]
I'll try it out if you let me know how to verify if it's working.

**Comment by stubailo** [comment]
I guess you could compare the css output with the old and new build system.

**Comment by tmeasday** [comment]
Done!
