### ISSUE TITLE
How to handle simulation errors

### ISSUE THREAD

**Issue by tmeasday** [meteor/todos#74]
For instance try removing the last public list.

Do we need to run all method calls like:

```js
try {
  doSomething.call(..., handleError);
} catch (e) {
  handleError(e);
}
```

(If so the wrapper should probably just do it. Did we decided validated-method would help with this?

**Comment by stubailo** [comment]
Yeah I think it should certainly help somehow... perhaps since it's impossible to get both a simulation and server exception, they should both go to the same callback?

**Comment by tmeasday** [comment]
Yes. There are conceivable situations where you might want to handle them differently, but maybe that should be a special argument to `validatedmethod.call()` (`{handleStubExceptions() {...}}`).

Want me to send a PR?

**Comment by stubailo** [comment]
@tmeasday let's figure out the design first. Do you think it's important to have separate callbacks or is it fine to just have the one `error` callback? We could easily have something like `error.isSimulation` or something as well.

**Comment by tmeasday** [comment]
Oh, `error.isSimulation` is good, I think I like that.

**Comment by hwillson** [comment]
Closing this off (simulation errors are handled by [mdg:validated-method](https://atmospherejs.com/mdg/validated-method)).
