### ISSUE TITLE
Can't create empty todo items

### ISSUE THREAD

**Issue by tmeasday** [meteor/todos#75]
The schema is failing if you remove all characters from a todo.

Do we need to make `todo.text` optional? Or stop empty strings from being cleaned somehow?

**Comment by stubailo** [comment]
Yeah maybe we should make it optional - but do we want to do this for new todos as well?

**Comment by tmeasday** [comment]
The current example doesn't let you create empty todos, but of course it only enforces this on the client side.

I guess we could set it to optional and check it in the method call for `insert` (which feels kind of crappy being out of the schema) or simply only enforce it client-side

**Comment by tmeasday** [comment]
Or we could figure out how to set that rule in the schema but I suspect it'll require quite a complex custom validator

**Comment by stubailo** [comment]
I don't think this is an important part of the example app, so maybe let's just allow empty todos.

**Comment by tmeasday** [comment]
Ok

**Comment by hwillson** [comment]
I've adjusted the Blaze version to allow empty todos (when updating). The React version already allows this. Closing this off - thanks!
