### ISSUE TITLE
Seems like fields validation error types is a mess

### ISSUE THREAD

**Issue by pronevich** [meteor/todos#77]
In Todos.schema we have field `text: {type: String, max: 100 }`, In ValidatedMethod 'Todos.methods.insert'  we use

`validate: new SimpleSchema({
    listId: { type: String },
    text: { type: String }
  }).validator(),`

and only when text field is not String we get error ValidationError, but when "text" field length is more than 100 this validation will be passed and then on Todos.insert(todo) attached schema validation will be executed that throws error 400 - not ValidationError.

`details: "[{"name":"text","type":"maxString","value":"example text longer than 100"}]"
error: 400
errorType: "Meteor.Error"
message: "Text cannot exceed 100 characters [400]"
reason: "Text cannot exceed 100 characters"`

As a result we have a problem in processing error types for form validation on client, because as recommended for fields validation  - look into ValidationError and than internationalize error messages for user.

**Comment by stubailo** [comment]
Sounds like we should refactor this to have something like `Todos.textSchemaType`, and then make sure to use the same thing in the collection schema and validator!

**Comment by pronevich** [comment]
If we have defined simple-schema on collection, that validated every time on insert, update and throws errors, why we need extra validation section(maybe just for some not collection data)? The bad part of default simple-schema is that in this case we get error "400", not error "validation-error"

**Comment by rhettlivingston** [comment]
Refactoring the schema isn't necessary. A combination of techniques like
```
  validate: Todos.simpleSchema().pick(['listId'], ['text']).validator({ clean: true, filter: false }),
```
which works nicely when the key names don't need to be changed and
```
  validate: new SimpleSchema({
    todoId: Todos.simpleSchema().schema('_id'),
    newText: Todos.simpleSchema().schema('text'),
  }).validator({ clean: true, filter: false }),
```
which works well when the keys do need to change or, if you don't want to define _id in your schemas,
```
const ID_SCHEMA = { type: String, regEx: SimpleSchema.RegEx.Id };
...
  validate: new SimpleSchema({
    todoId: ID_SCHEMA,
    newText: Todos.simpleSchema().schema('text'),
  }).validator({ clean: true, filter: false }),
```
which also isn't too bad, can achieve a **single point of schema definition** without refactoring the schema in possibly artificial ways to support methods.

I verified that simply using this technique in defining the validate options on all of the methods fixed the above-noted exception problem.

I'd be willing to create a PR.

**Comment by tmeasday** [comment]
Seems better now.
