### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by tab00** [meteor/todos#78]
After downloading the master branch, running `npm install` and `meteor`, the following error appears:

Error: Cannot find module './/D/Documents/Meteor/Projects/todos/i18n/en.i18n.json'

I'm using Microsoft Windows 10. Is it a path problem in Windows?

**Comment by stubailo** [comment]
@benjamn perhaps there is a problem with absolute paths on Windows?

**Comment by tmeasday** [comment]
@tab00 are you still seeing this on the 1.3 release?

**Comment by tab00** [comment]
I've tried it and it's working now.
