### ISSUE TITLE
Can't run app from master

### ISSUE THREAD

**Issue by stubailo** [meteor/todos#80]
@tmeasday I get some weird errors when I try to run the app.

```
➜  todos git:(master) ✗ meteor
[[[[[ ~/git/todos ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While selecting package versions:
   error: Potentially incompatible change required to top-level dependency: avital:mocha 2.1.0_6,
   was 2.1.0_8.
   Constraints on package "avital:mocha":

   To allow potentially incompatible changes to top-level dependencies, you must pass
   --allow-incompatible-update on the command line.

=> Your application has errors. Waiting for file change.
```

**Comment by tmeasday** [comment]
Hmmm. It works for me. 

I don't really understand the package system sometimes. What is it saying here? How does it make sense that you would allow any "updates" when simply running the tool?

Anyway, I'd try `meteor --allow-incompatible-update`

**Comment by tmeasday** [comment]
Or.. do you maybe have avital:mocha checked out somewhere?

**Comment by stubailo** [comment]
Yeah that didn't work too. Maybe it's related to submodules?

**Comment by tmeasday** [comment]
Do you have `PACKAGE_DIRS` set? We don't have that pkg as a submodule

**Comment by tmeasday** [comment]
Although I do see it in `.gitmodules`...

**Comment by tmeasday** [comment]
Do you have something in `packages/meteor-mocha`? I don't have it my app or a clean checkout. My guess is submodules being weird if so
