### ISSUE TITLE
Question: why using "imports" folder

### ISSUE THREAD

**Issue by Menda** [meteor/todos#81]
Hi, I have a question when I was looking to the code.

Why are you placing all the files which belong to client or server inside the `todos/import` folder? Why not just place them straight in `todos/server` or `todos/client`? Is it any new recommended new convention to write apps now in 1.3?

Thanks and greetings,
Rafa.

**Comment by vadimmelnicuk** [comment]
I am curious as well, because the structure is very different to the one adopted under Mantra.

**Comment by stubailo** [comment]
`imports` is a special directory name in Meteor 1.3. Files in there are not loaded unless explicitly imported. This lets you manage your file dependencies like you would in any other Node app, and avoid loading code you don't actually need.

**Comment by tmeasday** [comment]
Hopefully this article explains it for you: http://guide.meteor.com/v1.3/structure.html

If not let me know!

**Comment by Menda** [comment]
Thanks, everything is well explained. Greetings.
