### ISSUE TITLE
Utilizing `index.js` helps group & import app concerns as single directories/entry points

### ISSUE THREAD

**Issue by cheapRoc** [meteor/todos#84]
@stubailo [mentioned on the forum](https://forums.meteor.com/t/meteor-1-3-import-statements-everywhere/19007/14?u=cheaproc) this might be useful here.

Basically, this pattern helps enforce directories as a kind of "funnel", or nested entry point, for importing a module of functionality as a group, while still allowing individual files to be imported singularly.

Meteor 1.3's support of [Node's import rules](https://nodejs.org/api/modules.html#modules_all_together) provides the utility for importing as a directory. This pattern then utilizes a single `index.js` file defined within a directory as being responsible for maintaining the load order of the files contained within. Then you can simply import the directory as a single unit in order to import the files together, thus reducing external `import` statements.

**Example**

I ported over `/client/customer` and `/client/cart` each with their own set of files.  I created `/imports/ui/customer/index.js` then treated it as `import '/imports/ui/customer'`. This keeps the imports that wrap customer functionality tightly coupled to their dependent concerns (at least until more refactoring can take place). This worked well for `/imports/ui/*`, `/imports/api/schema` (for custom schema), `/imports/constants`, stuff like that.

I'm not entirely certain where this would work within the `todos` app but it's helped us lower the number of imports by grouping them closely together where appropriate.

**Comment by cheapRoc** [comment]
It's not as technical as it sounds, it's just `index.js` files. I can come up with a PR that demonstrates this for everyone but I'm unsure of where to implement it.

Maybe `import '/imports/startup/server'` and `import '/imports/startup/client'`?

**Comment by cheapRoc** [comment]
Might also help to align with future unit testing.

**Comment by tmeasday** [comment]
Yeah, and perhaps an `imports/api/lists/index.js` too? I'm not sure (I guess it would have to export things too?)

Anyway, please send that PR and we can discuss there.
