### ISSUE TITLE
Meteor Guide inconsistency.

### ISSUE THREAD

**Issue by Kamin12** [meteor/todos#89]

**Comment by Kamin12** [comment]
The code in the Meteor guide has templates named Lists_show_page, Lists_show. Can't seem to locate that code anywhere in this repo. Feel free to point me to the correct place if I am incorrect.

**Comment by stubailo** [comment]
https://github.com/meteor/todos/blob/master/imports/ui/pages/lists-show-page.js and https://github.com/meteor/todos/blob/master/imports/ui/pages/lists-show-page.html
