### ISSUE TITLE
Use useraccounts packages for login/signup

### ISSUE THREAD

**Issue by tmeasday** [meteor/todos#9]

**Comment by stubailo** [comment]
It's a little unfortunate that this app isn't build on a more "standard" CSS framework.. I feel like that will make this implementation much more complex

**Comment by tmeasday** [comment]
Welcome to the real world @stubailo :P

**Comment by stubailo** [comment]
Lol, in my real world all apps are generic bootstrap

**Comment by stubailo** [comment]
Dude... it was actually so easy. My mind is blown. Awesome, awesome work @splendido.

https://github.com/meteor/todos/commit/3ca9ad348661f2c665a180d7681eb0fb8466a465

**Comment by splendido** [comment]
Glad you liked it @stubailo!
...actually I'm surprised you pushed it so much without glitches, given the ugly guide! ;-)

I definitely need to improve the documentation and better organize all good information spread across issues :(
