### ISSUE TITLE
Wekan favicon?

### ISSUE THREAD

**Issue by batjko** [meteor/todos#91]
Seems like Todos app uses the Wekan favicon for some reason?
![image](https://cloud.githubusercontent.com/assets/7287076/14110500/9703d3a0-f5be-11e5-9478-785eee5c4970.png)

**Comment by stubailo** [comment]
Hmm, it should be this icon: https://github.com/meteor/todos/blob/master/public/favicon.png

I wonder why it doesn't work!

**Comment by batjko** [comment]
Thinking about it... it may actually be my own stupid browser cache. I do remember I had a local Wekan installation running ages ago.

I'll check that tomorrow and probably close this. Should have thought of it before.

**Comment by dburles** [comment]
Yep it's cache

**Comment by batjko** [comment]
Yup, clearing the cache solved the problem. Weird, but makes sense.
Closing.
