### ISSUE TITLE
"Cannot find eslint-plugin-meteor" Error

### ISSUE THREAD

**Issue by batjko** [meteor/todos#92]
Hi guys,

This could be a problem with the Atom editor or the fast-eslint package I am using with it, but just to be sure, I thought I confirm here:

I have done a successful `npm install` and then got this error. Afterwards, I also did an explicit `npm install eslint-plugin-meteor`, which also seemed successful.

And yet, this keeps popping up:
![image](https://cloud.githubusercontent.com/assets/7287076/14110897/724d0b88-f5c0-11e5-8ada-290e8b7148d6.png)

**Comment by bitsuns** [comment]
I'm using Atom and didn't have this problem. Maybe it's the fast-eslint package or another dependency?

**Comment by batjko** [comment]
Yea, I switched back to the more mainstream `linter-eslint` package and it's fine now.
Closing.
