### ISSUE TITLE
fails on 1.3

### ISSUE THREAD

**Issue by interfaith** [meteor/todos#93]
stem-Product-Name:~/todos$ meteor npm install --save faker
npm WARN package.json @ No repository field.
faker@3.1.0 node_modules/faker
stem-Product-Name:~/todos$ meteor
[[[[[ ~/todos ]]]]]                           

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While minifying app stylesheet:
   error: Can't load npm module 'autoprefixer' from packages/minifier-postcss_plugin.js. Check your Npm.depends().
   
=> Your application has errors. Waiting for file change.

**Comment by stubailo** [comment]
Did you run `npm install` in the app? `autoprefixer` is listed as an NPM dependency in `package.json`: https://github.com/meteor/todos/blob/master/package.json

**Comment by interfaith** [comment]
npm install --save
was enough , the new normal for 1.3

**Comment by stubailo** [comment]
Yep!
