### ISSUE TITLE
Cannot build Android cordova app

### ISSUE THREAD

**Issue by wiserweb** [meteor/todos#99]
Note: I have only attempted on Linux and do not know if this issue exists on other platforms.

sdk: 23.0.3
meteor: 1.3
os: ubuntu/mint latest stable 17.3 64bit
java: 1.8.0_77-b03

steps to reproduce:
git clone git@github.com:meteor/todos.git todos13
cd todos13
npm install
meteor update
meteor build /home/user/output/todos13-local/ --debug --server=http://192.168.1.8:3000

console output:
BUILD SUCCESSFUL

Total time: 23.022 secs

However no release-unsigned.apk is in the output folder.

**Comment by rwatts3** [comment]
I too am experiencing the same issue. 
Not sure why this is happening.

**Comment by hwillson** [comment]
@wiserweb @rwatts3 - Is this issue still happening? If so could you try a more recent version of todos (leveraging a more recent version of Meteor), and post back with your results? Thanks!

**Comment by rwatts3** [comment]
Sorry this is no longer happening for me as I've now been using the new
version.

I would like to ask if the react branch is ssr ?

**Comment by hwillson** [comment]
> I would like to ask if the react branch is ssr ?

No, not currently.

**Comment by hwillson** [comment]
Thanks for your feedback @rwatts3 - I'll close this off for now (post back if anything changes).
